name: 'FTP Smart File Copy'
description: '.NET-based GitHub Action to copy files over FTP.'
branding:
  icon: arrow-up-circle
  color: white
inputs:
  server:
    description:
      'Address for the destination server.'
    required: true
  port:
    description:
      'Port for the destination server.'
    required: false
    default: 21
  username:
    description:
      'Username for the destination server.'
    required: true
  password:
    description:
      'Password for the destination server.'
    required: true
  source:
    description:
      'Directory in source from which to upload.'
    required: true
    default: '/'
  destination:
    description:
      'Directory in destination to which to upload.'
    required: true
    default: '/'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '--server'
  - ${{ inputs.server }}
  - '--port'
  - ${{ inputs.port }}
  - '--username'
  - ${{ inputs.username }}
  - '--password'
  - ${{ inputs.password }}
  - '--source'
  - ${{ inputs.source }}
  - '--destination'
  - ${{ inputs.destination }}